### ISSUE TITLE
Can't install pypa in python 3.8.2

### ISSUE THREAD

**Issue by michael-shaked** [vladimarius/pyap#19]
Hi,

Thanks for your great work! when I try to install I got this error:

`(venv) User@SOZ-MBP16 sample_project % pip install pypa
Collecting pypa
  Downloading pyPA-1.0rc.tar.gz (38 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/User/PycharmProjects/sample_project/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6k/6tmz3rc91759jdxs80_fjd180000gp/T/pip-install-4z09r1ik/pypa_857e7edb458246b0bbdc50f992f13718/setup.py'"'"'; __file__='"'"'/private/var/folders/6k/6tmz3rc91759jdxs80_fjd180000gp/T/pip-install-4z09r1ik/pypa_857e7edb458246b0bbdc50f992f13718/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/6k/6tmz3rc91759jdxs80_fjd180000gp/T/pip-pip-egg-info-tkpdibrw
         cwd: /private/var/folders/6k/6tmz3rc91759jdxs80_fjd180000gp/T/pip-install-4z09r1ik/pypa_857e7edb458246b0bbdc50f992f13718/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6k/6tmz3rc91759jdxs80_fjd180000gp/T/pip-install-4z09r1ik/pypa_857e7edb458246b0bbdc50f992f13718/setup.py", line 17
        except ImportError, e:
                          ^
    SyntaxError: invalid syntax
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bc/5a/2964cadcb8bc8d875768a16f023abb328deb895fad65fb1406dd3abc6219/pyPA-1.0rc.tar.gz#sha256=8c5f32fed2f192bd2c07912f17e3f770ec3e09ebae2aef4091171dcdca875c72 (from https://pypi.org/simple/pypa/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

Do you know what is the problem?
I am running on Macos python 3.8.2

**Comment by vladimarius** [comment]
The package is name **pyap** not _pypa_
😂

**Comment by michael-shaked** [comment]
Hi, can you delete the issue please?
