### ISSUE TITLE
French addresses

### ISSUE THREAD

**Issue by vandelouw** [vladimarius/pyap#6]
Hi Vladimarius,
do you know if some work has been done on french addresses ? I have to parse some french addresses, it seems libpostal is nice but I have problems installing it and I found no other reliable solution, do you know other parsers for international addresses ?
Thanks for your work !
Romain

**Comment by vladimarius** [comment]
Hi Vandelouw,
I haven't seen any work on French addresses. As for libpostal - afaik, this lib does slightly different thing, it splits address into pieces (street name, number, city, ...). Pyap does this also, but is mainly used for quick finding of address string inside a larger text containing things which might not be addresses.

Vlad
